
    - name: Configuration
      delegate_to: localhost
      community.vmware.vmware_guest:
        validate_certs: false
        hostname: "{{ vsphere_ip }}"  
        username: "{{ vsphere_username }}"
        password: ""
        folder: ""
        name: ""
        state: poweredoff
        guest_id: ""
        disk: ""
        datastore: "hno200_dev_vmw_data1"
        hardware: 
          boot_firmware: efi
          memory_mb: ""
          num_cpus: ""
          num_cpu_cores_per_socket: ""
          scsi: paravirtual
        networks:
          connect: yes
          mac: ""
          ip: ""
          netmask: ""
          device_type: wmxnet3
          type: static
          register: deploy_vm
          throttle: 5

    - name: Ajout d'un disque bootable (Rocky Linux)
      community.vmware.vmware_guest_disk:
        validate_certs: false
        hostname: ""
        username: ""
        password: ""
        name: ""
        datacenter: ha-datacenter
        disk:
          - filename: ""
            scsi_type: paravirtual
            sci_controller: 0
            unit_number: 1
            register: disk_facts

    - name: démarrage de la VM
      community.vmware.vmware_guest:
        hostname: ""
        username: ""
        password: ""
        name: ""
        state: poweredon
        wait_for_ip_address: yes
        delegate_to : ""